version: "3.9"
services:
  vault-dev:
    container_name: vault-dev
    image: vault:1.10.0
    ports:
      - "8200:8200/tcp"
    # envs and volumes are optional
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: 'root'
      # VAULT_DEV_LISTEN_ADDRESS: '0.0.0.0:8200'
    # volumes:
    #   - /vault/data
    #   - /etc/vault/logs
        
  # vault-agent:
  #   container_name: vault-agent
  #   image: 


